modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="playerupgrades"
version="2.0.0"
displayName="Player Upgrades"
displayURL="https://modmonster.ca"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ModMonster"
description="A mod that adds upgrades to enhance your player!"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.playerupgrades]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.playerupgrades]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration